var AppDispatcher = require('../Dispatcher/AppDispatcher.js');

var CardAction = {
	receiveCards:function(data){
		AppDispatcher.handleAction({
			actionType:'RECEIVE_CARDS',
			data:data
		})
	},
	receiveNewCards:function(data){
		AppDispatcher.handleAction({
			actionType:'RECEIVE_NEW_CARDS',
			data:data
		})
	},
	emptyNewCards:function(){
		AppDispatcher.handleAction({
			actionType:'EMPTY_NEW_CARDS'
		})
	},
	updateCard:function(data){
		AppDispatcher.handleAction({
			actionType:'UPDATE_CARD',
			data:data
		})
	},
	updateAB:function(data){
		AppDispatcher.handleAction({
			actionType:'UPDATE_AB',
			data:data
		})
	},
	emptyAB:function(){
		AppDispatcher.handleAction({
			actionType:'EMPTY_AB'
		})
	},
	updateABImage:function(data){
		AppDispatcher.handleAction({
			actionType:'UPDATE_AB_IMAGE',
			data:data
		})
	},
	updateLike:function(data){
		AppDispatcher.handleAction({
			actionType:'UPDATE_LIKE',
			data:data
		})
	},
	updateImage:function(data){
		AppDispatcher.handleAction({
			actionType:'UPDATE_IMAGE',
			data:data
		})
	},
	updateImageLike:function(data){
		AppDispatcher.handleAction({
			actionType:'UPDATE_IMAGE_LIKE',
			data:data
		})
	},
	createVote:function(data){
		AppDispatcher.handleAction({
			actionType:'CREATE_VOTE',
			data:data
		})
	},
	updateVote:function(data){
		AppDispatcher.handleAction({
			actionType:'UPDATE_VOTE',
			data:data
		})
	},
	receiveAB:function(data){
		AppDispatcher.handleAction({
			actionType:'RECEIVE_AB',
			data:data
		})
	},
	endOfData:function(data){
		AppDispatcher.handleAction({
			actionType:'END_OF_DATA',
			data:data
		})
	}
}

module.exports = CardAction;